title: Dana Amundsen
description: The New Layout
theme: jekyll-theme-architect

body_font: Karla #font used for body text
header_font: Berkshire Swash #font used for title and header

font_color: "#241C07"
background_color: "#fff"
color1: "#241C07" #color of links and headers
color2: "#A17649" #color of links on hover
