title: Dana Amundsen
description: The New Layout
theme: jekyll-theme-architect

body_font: Roboto Slab #font used for body text
header_font: Vast Shadow #font used for title and header

font_color: "#000"
background_color: "#fff"
color1: "#aaa" #color of links and headers
color2: "#ccc" #color of links on hover
